version: "3.5"
services:
  blog-lumen:
    image: aronnebrivio/php:8.0-dev
    container_name: blog-lumen
    environment:
      - XDEBUG_MODE=${XDEBUG_MODE}
    user: "www-data:www-data"
    volumes:
      # code
      - .:/var/www/html:cached
      # container /tmp folder, used for profiler and other stuff
      - ./private/tmp:/tmp:delegated
    ports:
      - ${PHP_HOST_PORT}:80
    networks:
      backend:
        aliases:
          - blog-lumen

  blog-db:
    image: mysql:8
    # Set DB_HOST variable in .env file to this value to use local environment
    container_name: blog-db
    volumes:
      # The db files are stored in this named volume
      - blog-db-data:/var/lib/mysql:delegated
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    ports:
      - ${MYSQL_HOST_PORT}:3306
    networks:
      backend:
        aliases:
          - blog-db

  blog-redis:
    image: redis
    container_name: blog-redis
    volumes:
      # The db files are stored in this named volume
      - blog-redis-data:/data:delegated
    environment:
      - REDIS_URL=redis://${REDIS_HOST}:${REDIS_PORT}
      - REDIS_DATABASE=${REDIS_DATABASE}
    ports:
      - ${REDIS_HOST_PORT}:${REDIS_PORT}
    networks:
      backend:
        aliases:
          - blog-redis

volumes:
  blog-db-data:
    driver: local
  blog-redis-data:
    driver: local

networks:
  backend:
    name: blog-network
